### ISSUE TITLE
llama_index_sentence_splitter issues 

### ISSUE THREAD

**Issue by deter3** [bclavie/RAGatouille#66]
Using llama_index and langchain will always bring lots of debug problem .  There wrapper code design is just a mess.  

Traceback (most recent call last):
  File "/workspace/three_methods_ranking2.py", line 160, in <module>
    my_documents = processor.process_corpus(documents)
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/data/corpus_processor.py", line 22, in process_corpus
    documents = self.document_splitter_fn(documents, **splitter_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ragatouille/data/preprocessors.py", line 9, in llama_index_sentence_splitter
    docs = [[Document(text=doc)] for doc in documents]
TypeError: 'NoneType' object is not iterable

**Comment by bclavie** [comment]
Hey, could you provide more of your code? It looks like the issue here is that the `documents` that makes it to the preprocessor is None, so would be helpful to figure out how that happened!

**Comment by manisnesan** [comment]
@bclavie - I faced a similar issue when I ran the notebook [06-index_free_use.ipynb](https://github.com/bclavie/RAGatouille/blob/main/examples/06-index_free_use.ipynb) from `examples`.  

Tried to create a reproducer in the code using [Colab](https://colab.research.google.com/drive/1lbqVARtIlvE4DXF8rXqKTPEM4LPqe1rR?usp=sharing) and faced 

```
ValidationError: 1 validation error for Document
text
  none is not an allowed value (type=type_error.none.not_allowed)
  ```
  
 The root cause is due to one of the page being empty and hence ragatouille is throwing the error as "ValidationError" which is the right behavior. 

The user need to ensure passing only valid docs before passing to `Corpus_Processor.process_corpus` method. This issue is not a bug and can be closed.
