### ISSUE TITLE
Batch search in-memory without index results in TypeError if you pass document_metadatas

### ISSUE THREAD

**Issue by bjsi** [bclavie/RAGatouille#79]
My code:

```python
def rag(args: SearchArgs) -> List[List[SearchResult]]:
    RAG = RAGPretrainedModel.from_pretrained("colbert-ir/colbertv2.0", verbose=0)
    metadata = [doc["metadata"] for doc in args["docs"]]
    RAG.encode(
        [doc["content"] for doc in args["docs"]],
        document_metadatas=metadata,
    )
    k = args.get("k", 5)
    search_results = RAG.search_encoded_docs(query=args["query"], k=k)
    
res = rag(
    {
        "query": ["Hello World", "This is a test"],
        "docs": [
            {"content": "doc1", "metadata": {"id": 0}},
            {"content": "doc2", "metadata": {"id": 1}},
        ],
    }
)
```

Error:

```
Documents encoded!
Traceback (most recent call last):
  File "/Users/james/Projects/TS/open-recommender/packages/cli/src/rag/rag.py", line 996, in <module>
    res = rag(
          ^^^^
  File "/Users/james/Projects/TS/open-recommender/packages/cli/src/rag/rag.py", line 37, in rag
    search_results = RAG.search_encoded_docs(query=args["query"], k=k)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Projects/TS/open-recommender/env/lib/python3.11/site-packages/ragatouille/RAGPretrainedModel.py", line 377, in search_encoded_docs
    return self.model.search_encoded_docs(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/james/Projects/TS/open-recommender/env/lib/python3.11/site-packages/ragatouille/models/colbert.py", line 722, in search_encoded_docs
    result["result_index"]
    ~~~~~~^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

One thing I found confusing, and which seems to be causing this error too, is that `search_encoded_docs` returns either `List[SearchResult]` or a nested `List[List[SearchResult]]` depending on the number of queries. Maybe it would be better to just always return `List[List[SearchResult]]` otherwise we have to implement conditional logic based on the number of queries we pass, which we might not know ahead of time?

**Comment by bclavie** [comment]
Hey, thank you for flagging. You're pretty much right on point as to what's going on. The search results should really be migrated to validated pedantic objects (soon ™️) to avoid further issues of this kind.

I think for now (to avoid breaking workflows), we'll stick with `List[SearchResults] | List[List[SearchResults]]`, and update the post-processing logic accordingly, though unifying the return type in the future would probably be a good shout.

(will fix this particular issue in a release soon!)

**Comment by bjsi** [comment]
Sounds good, thanks a lot!
